urxvtd &
xrdb -merge ~/.Xresources
xrandr --output GPU-0.HDMI-0 --off --output GPU-0.DP-0 --off --output GPU-0.DP-2 --off --output GPU-0.DP-3 --off --output GPU-0.DP-4 --off --output GPU-0.DP-5 --off --output GPU-0.DP-1 --off --output GPU-1.DP-3 --off --output GPU-1.DVI-I-1 --mode 1680x1050 --pos 0x0 --rotate normal --output GPU-1.DP-1 --mode 1680x1050 --pos 3360x0 --rotate normal --output GPU-1.HDMI-0 --off --output GPU-0.DVI-I-0 --off --output GPU-0.DVI-I-1 --mode 1680x1050 --pos 1680x0 --rotate normal --output GPU-1.DP-5 --off --output GPU-1.DVI-I-0 --off --output GPU-1.DP-0 --off --output GPU-1.DP-2 --off --output GPU-1.DP-4 --off
xscreensaver -nosplash &
awesome
